### PR TITLE
try remove noinit

### PR DESCRIPTION
**Pull request by Clonkk**

### CODE REVIEW

**Comment by Clonkk** [comment]
Just noticed that the workaround to avoid templated declaration: 
```
/home/clonkk/.cache/nim/test_accessors_slicer_d/@m..@s..@sflambeau@stensors.nim.cpp:34:9: error: ‘at::Tensor’ is not a template
   34 | typedef torch::Tensor<NF>  TY__PrdnljbGhfFRNRu5jD7C3g;
      |         ^~~~~
```
 doesn't work on devel but work on v1.6.2 :/

File: flambeau/tensors/interop.nim [hunk 1]
```diff
@@ -26,38 +26,32 @@ func toTensorView*[T: SomeTorchType](oa: openArray[T]): lent Tensor[T] =
...
+  # Don't know why clone is segfaulting so it seems easier to just copyMem the openArray
+  let shape = getShape(arg).toSeq()
+  result = empty[T](shape)
+  let memlen = (arg.len()*sizeof(T)) div sizeof(byte)
+  let data = result.data_ptr()
+  copyMem(data, arg[0].unsafeAddr, memlen)
 
-template toTensorImpl[T: SomeTorchType](a: untyped) : Tensor[T] = 
-  asTensor[T](toRawTensor(a))
+func toTensorFromSeq*[T: seq|array, U](oa: openarray[T]): Tensor[U] =
```
Comment (mratsim) [inline flambeau/tensors/interop.nim:43]: Can't we use overloading instead of spelling FromScalar and FromSeq?

File: flambeau/tensors/mathalgo.nim [hunk 2]
```diff
@@ -8,19 +8,31 @@ import std/[complex, macros]
...
-  result.values = asTensor[T](cppSortTuple.get(0).clone())
-  result.originalIndices = asTensor[int64](cppSortTuple.get(1).clone())
+  let 
+    cppSortTuple = rawtensors.sort(asRaw(self), axis, descending)
+    tmp1 = asTensor[T](cppSortTuple.get(0))
+    tmp2 = asTensor[int64](cppSortTuple.get(1))
+  debugecho "<=========================>"
+  debugecho tmp1
+  debugecho tmp2
+  debugecho "<=========================>"
```
Comment (mratsim) [inline flambeau/tensors/mathalgo.nim]: Debug left

Comment (Clonkk) [reply flambeau/tensors/mathalgo.nim]: I don't see those on my local branch or on latest commit of the PR

File: flambeau/tensors/interop.nim (hunk 1 above)
Comment (Clonkk) [reply flambeau/tensors/interop.nim:43]: It's kinda what's already been done.

``toTensorFromSeq`` / ``toTensorFromScalar`` are helpers proc and the API is ``toTensor``.  Arguably, they could be made private

**Comment by Clonkk** [comment]
https://github.com/nim-lang/Nim/pull/21378 related. removing zeroMem on init would with Flambeau

**Comment by Clonkk** [comment]
@Vindaar @HugoGranstrom 

Is it reaonable to merge this once 2.0 is out and restrict Flambeau to 2.0 and above ?

**Comment by HugoGranstrom** [comment]
I'm all for Flambeau (and all other *new/not yet officially published* libraries in scinim) to require Nim v2.0 if they require it for our own sanity. In my mind Flambeau hasn't been officially released and is still beta, so making restrictions like this is totally fine by me. 

Datamancer, Arraymancer, numericalnim, ggplotnim etc should still work with the old versions as long as it doesn't cause too much work to maintain alongside v2.0.

**Comment by Clonkk** [comment]
Since we are all in agreement, I added the Nim version guard and I will merge as soon as PR is done :)
